### ISSUE TITLE
Missed re-exported classes

### ISSUE THREAD

**Issue by eilrix** [unstubbable/typedoc-plugin-monorepo#12]
Hi! I have a problem generating docs after update to typedoc 0.21.5.
This package prevents typedoc to output re-exported classes. Although names of such classes are still listed as "References", these references have links to themselves. 
It has an exception: if a re-export goes alphabetically before file-exporter, then it will appear in the output as class nonetheless.

The issue sounds weird, but I spent hours trying to understand this bug, when some classes were showing, another won't. 
Eventually, I managed to make a workaround by renaming my `index.ts` to `_index.ts`, so it will always go alphabetically last. 

Here small reproduction case:
https://github.com/eilrix/typedoc-plugin-monorepo-bug

I tried old versions, 0.3.1 works without this problem, though I had to [put a fix](https://github.com/eilrix/typedoc-plugin-monorepo/commit/799a0847e3cf82d6a67048e44784fe8cd16252bc) to make it work with typedoc 0.21.5

**Comment by SkReD** [comment]
https://github.com/unstubbable/typedoc-plugin-monorepo/pull/13 solves this in the way of replacing references with actual declarations

**Comment by eilrix** [comment]
@SkReD Hey! I built your repo and copied files into my reproduction repo, added `"inline-references": true` into my typedoc config,  but result is still the same

**Comment by SkReD** [comment]
Indeed. Strange. I'll have a closer look why is this happening

**Comment by unstubbable** [comment]
This project is deprecated since [TypeDoc now supports monorepos out of the box](https://typedoc.org/guides/monorepo/).
