### ISSUE TITLE
Support for TS4.x and Typedoc 0.19

### ISSUE THREAD

**Issue by maneetgoyal** [unstubbable/typedoc-plugin-monorepo#6]
Hello @unstubbable 👋 ,

We are using TS4.x and Typedoc 0.19 in a monorepo setup. Using this plugin alongside. Do you envision any issues if we use TS4.x syntax in our source code given this plugin uses different version for TS and Typedoc?

**Comment by maneetgoyal** [comment]
For completeness, I have not run into any doc generation errors yet.

**Comment by unstubbable** [comment]
shipped with [v0.4.1](https://www.npmjs.com/package/@strictsoftware/typedoc-plugin-monorepo/v/0.4.1)
