### ISSUE TITLE
Typedoc 0.20 compatibility

### ISSUE THREAD

**Issue by yoursunny** [unstubbable/typedoc-plugin-monorepo#7]
This plugin appears incompatible with Typedoc 0.20 version.
For starters, `mode` and `ignoreCompilerErrors` options mentioned in README of this plugin are removed in Typedoc 0.20.

**Comment by unstubbable** [comment]
shipped with [v0.4.1](https://www.npmjs.com/package/@strictsoftware/typedoc-plugin-monorepo/v/0.4.1)
